# fly.toml app configuration file generated for nse-moves

app = 'nse-moves'
primary_region = 'bom'

# Note: The [build] section was removed to force Fly.io to build using your Dockerfile.

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
