# fly.toml app configuration file generated for nse-moves on 2026-05-22T18:02:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nse-moves'
primary_region = 'bom'

[env]
  PORT = '8080'

[processes]
  app = "python bot.py"

# No http_service needed for a background bot

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
